services:
  - type: web
    name: uploaderpage
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9   # Force Python 3.11
      - key: SUPABASE_URL
        sync: false     # Youâ€™ll set these in Render dashboard
      - key: SUPABASE_KEY
        sync: false

